os:
  - linux
dist: trusty
sudo: false
language: generic
env:
  matrix:
    - TEX=lualatex
    - TEX=uplatex
  global:
    secure: SyIQNXB0IJDxpiIQm71mviG8JZ84pdU4m1aRiZqpUb49WI4ppbwqQ67s9VTBp8PE16+uxS8wFCZvqrP+/5CcgSaD6ENqCqiPUJEKmsEkJ2NzgnceN7GZnLIoboglpWKn3/Z9SmIEZ3RSanmIo+gAiDlyFzxtyB7/m9ZE4S3HBVi7gmpn+GF7N4+OPJjM1wNkq+QXJ869F9eokvfHX8pADo1vn65vi/nPSkJBT68IsYMTyladYfW1e1K27/w+//qmll5JIVk2+KFG5dwRaqjt2zA1gJui9at3AMet1Ti+unzHJfDRTTJIR/4qfec8uCIoSPzpqtALxLc5DPXapwBdFi5LkhCbujxVZ9XhFcCFVEgqRc6/NpyqkA8gRypaZTlToEwbkeWrHFZ1AyjDz1sqcltyU98j1W7CofL57g3/SJc4dzQ8bSNIA4xccCES2tkaSbjYbCSY3+9eWg2M3ALBQfpgnvnnfGmqIHRufrXcqRs04ogf87Lbu8rtbrs7kDgb15OEEjcLQQldxSAr1Ynz391KTtJa+K8mbIbe+foXbrInb5qI4KFMxU5ihz6QaILZ0l1k2l17nQDuvy69YnVfBNo35sdJk4kfHc4JUqpFjEzNkHxXKIiWt+1w2y5qwC4aWWO1tv9PN6D+gKYYsulWsyXkhK6Kgzs3BwW7EouYGLU=
before_install:
  - openssl aes-256-cbc -k "$PASSWORD" -in handbook.zip.enc -d -a -out handbook.zip
  - unzip handbook.zip
  - cd handbook
install:
  - wget https://raw.githubusercontent.com/y-yu/install-tex-travis/master/install-tex.sh
  - chmod +x install-tex.sh
  - . ./install-tex.sh
  - tlmgr install collection-luatex collection-fontsrecommended
    collection-langjapanese latexmk enumitem piff menukeys everyhook svn-prov
    xstring adjustbox collectbox relsize catoptions cprotect bigfoot ifptex type1cm
script:
  - if [[ "$TEX" = 'lualatex' ]]; then
      lualatex main && lualatex main && lualatex main;
    else
      uplatex main && uplatex main && uplatex main;
      dvipdfmx main;
    fi
